name: Publish on Tag

on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build
        run: cargo build --verbose
      - name: Cargo Login
        env:
          CRATESIO_API_TOKEN: ${{ secrets.CRATESIO_API_TOKEN }}
        run: cargo login ${CRATESIO_API_TOKEN}
      - name: Cargo Test
        env:
          TEST_OPTS: --verbose
        run: ./bin/test.sh
      - name: Cargo Publish
        run: ./bin/publish.sh
